import {
  RoadSegment,
  Junction,
  TrafficIncident,
  CascadeEvent,
  CascadeRelationship,
  ScenarioResult,
  RouteAlternative,
  CitizenAlert,
  SystemServiceStatus,
  OperatorAction
} from '../types/traffic';

// Demo Corridor: Metropolitan Central Arterial Corridor (J1 to J10)
// Base coordinates around City Central Grid (e.g. 13.0827° N, 80.2707° E)
export const CORRIDOR_JUNCTIONS: Junction[] = [
  {
    id: 'j1',
    code: 'J1',
    name: 'North Outer Gateway',
    type: 'SIGNALIZED',
    coordinates: [80.2520, 13.0980],
    currentQueueMeters: 45,
    capacityPressurePercent: 42,
    currentPhaseSecondsRemaining: 24,
    riskSeverity: 'LOW',
    spillbackProbabilityPercent: 8,
    connectedSegments: ['seg-1-2']
  },
  {
    id: 'j2',
    code: 'J2',
    name: 'Tech Boulevard Interchange',
    type: 'INTERSECTION',
    coordinates: [80.2580, 13.0910],
    currentQueueMeters: 80,
    capacityPressurePercent: 58,
    currentPhaseSecondsRemaining: 18,
    riskSeverity: 'LOW',
    spillbackProbabilityPercent: 14,
    connectedSegments: ['seg-1-2', 'seg-2-3', 'seg-2-9']
  },
  {
    id: 'j3',
    code: 'J3',
    name: 'Civic Center Cross',
    type: 'SIGNALIZED',
    coordinates: [80.2640, 13.0850],
    currentQueueMeters: 110,
    capacityPressurePercent: 68,
    currentPhaseSecondsRemaining: 12,
    riskSeverity: 'MODERATE',
    spillbackProbabilityPercent: 28,
    connectedSegments: ['seg-2-3', 'seg-3-4', 'seg-3-10']
  },
  {
    id: 'j4',
    code: 'J4',
    name: 'Metro West Station',
    type: 'SIGNALIZED',
    coordinates: [80.2690, 13.0790],
    currentQueueMeters: 95,
    capacityPressurePercent: 62,
    currentPhaseSecondsRemaining: 30,
    riskSeverity: 'MODERATE',
    spillbackProbabilityPercent: 34,
    connectedSegments: ['seg-3-4', 'seg-4-5']
  },
  {
    id: 'j5',
    code: 'J5',
    name: 'Grand Trunk Junction',
    type: 'SIGNALIZED',
    coordinates: [80.2740, 13.0730],
    currentQueueMeters: 140,
    capacityPressurePercent: 78,
    currentPhaseSecondsRemaining: 15,
    riskSeverity: 'MODERATE',
    spillbackProbabilityPercent: 46,
    connectedSegments: ['seg-4-5', 'seg-5-6', 'seg-5-7']
  },
  {
    id: 'j6',
    code: 'J6',
    name: 'Harbor Link Approach',
    type: 'MERGE',
    coordinates: [80.2710, 13.0660],
    currentQueueMeters: 195,
    capacityPressurePercent: 88,
    currentPhaseSecondsRemaining: 8,
    predictedEvent: 'DOWNSTREAM_BLOCKING',
    riskSeverity: 'HIGH',
    spillbackProbabilityPercent: 64,
    connectedSegments: ['seg-5-6', 'seg-6-7']
  },
  {
    id: 'j7',
    code: 'J7',
    name: 'Central Plaza Apex (Critical)',
    type: 'SIGNALIZED',
    coordinates: [80.2790, 13.0680],
    currentQueueMeters: 280,
    capacityPressurePercent: 94,
    currentPhaseSecondsRemaining: 5,
    predictedEvent: 'SPILLBACK',
    riskSeverity: 'CRITICAL',
    spillbackProbabilityPercent: 72,
    connectedSegments: ['seg-5-7', 'seg-6-7', 'seg-7-8']
  },
  {
    id: 'j8',
    code: 'J8',
    name: 'Hospital Corridor North',
    type: 'SIGNALIZED',
    coordinates: [80.2850, 13.0620],
    currentQueueMeters: 165,
    capacityPressurePercent: 79,
    currentPhaseSecondsRemaining: 20,
    predictedEvent: 'DIVERSION_OVERLOAD',
    riskSeverity: 'HIGH',
    spillbackProbabilityPercent: 53,
    connectedSegments: ['seg-7-8', 'seg-8-9']
  },
  {
    id: 'j9',
    code: 'J9',
    name: 'City General Hospital Apex',
    type: 'ROUNDABOUT',
    coordinates: [80.2920, 13.0560],
    currentQueueMeters: 65,
    capacityPressurePercent: 45,
    currentPhaseSecondsRemaining: 35,
    riskSeverity: 'LOW',
    spillbackProbabilityPercent: 12,
    connectedSegments: ['seg-2-9', 'seg-8-9']
  },
  {
    id: 'j10',
    code: 'J10',
    name: 'South Ring Expressway Entry',
    type: 'INTERSECTION',
    coordinates: [80.2800, 13.0500],
    currentQueueMeters: 50,
    capacityPressurePercent: 38,
    currentPhaseSecondsRemaining: 40,
    riskSeverity: 'LOW',
    spillbackProbabilityPercent: 9,
    connectedSegments: ['seg-3-10']
  }
];

export const CORRIDOR_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-1-2',
    name: 'North Arterial Section 1',
    fromJunction: 'J1',
    toJunction: 'J2',
    lengthMeters: 950,
    currentSpeedKmh: 46,
    freeFlowSpeedKmh: 50,
    capacityStressPercent: 38,
    estimatedQueueMeters: 30,
    blockingPercent: 6,
    flowVehiclesPerHour: 1420,
    densityVehiclesPerKm: 31,
    vehicleComposition: { cars: 48, twoWheelers: 32, buses: 6, heavyVehicles: 4, autos: 10 },
    classification: 'OBSERVED',
    freshness: 'FRESH',
    lastUpdatedSecondsAgo: 8,
    predictedRisk: 'LOW',
    confidencePercent: 92,
    coordinates: [[80.2520, 13.0980], [80.2550, 13.0945], [80.2580, 13.0910]]
  },
  {
    id: 'seg-2-3',
    name: 'Tech Blvd Main Connector',
    fromJunction: 'J2',
    toJunction: 'J3',
    lengthMeters: 1100,
    currentSpeedKmh: 38,
    freeFlowSpeedKmh: 45,
    capacityStressPercent: 54,
    estimatedQueueMeters: 65,
    blockingPercent: 12,
    flowVehiclesPerHour: 1850,
    densityVehiclesPerKm: 48,
    vehicleComposition: { cars: 52, twoWheelers: 28, buses: 8, heavyVehicles: 2, autos: 10 },
    classification: 'OBSERVED',
    freshness: 'FRESH',
    lastUpdatedSecondsAgo: 12,
    predictedRisk: 'LOW',
    confidencePercent: 88,
    coordinates: [[80.2580, 13.0910], [80.2610, 13.0880], [80.2640, 13.0850]]
  },
  {
    id: 'seg-3-4',
    name: 'Civic Link Expressway',
    fromJunction: 'J3',
    toJunction: 'J4',
    lengthMeters: 850,
    currentSpeedKmh: 31,
    freeFlowSpeedKmh: 45,
    capacityStressPercent: 64,
    estimatedQueueMeters: 90,
    blockingPercent: 18,
    flowVehiclesPerHour: 1980,
    densityVehiclesPerKm: 64,
    vehicleComposition: { cars: 45, twoWheelers: 35, buses: 9, heavyVehicles: 3, autos: 8 },
    classification: 'ESTIMATED',
    freshness: 'FRESH',
    lastUpdatedSecondsAgo: 15,
    predictedRisk: 'MODERATE',
    confidencePercent: 84,
    coordinates: [[80.2640, 13.0850], [80.2665, 13.0820], [80.2690, 13.0790]]
  },
  {
    id: 'seg-4-5',
    name: 'Metro West Corridor',
    fromJunction: 'J4',
    toJunction: 'J5',
    lengthMeters: 920,
    currentSpeedKmh: 28,
    freeFlowSpeedKmh: 45,
    capacityStressPercent: 72,
    estimatedQueueMeters: 120,
    blockingPercent: 24,
    flowVehiclesPerHour: 2150,
    densityVehiclesPerKm: 76,
    vehicleComposition: { cars: 42, twoWheelers: 38, buses: 10, heavyVehicles: 2, autos: 8 },
    classification: 'ESTIMATED',
    freshness: 'FRESH',
    lastUpdatedSecondsAgo: 10,
    predictedRisk: 'MODERATE',
    confidencePercent: 85,
    coordinates: [[80.2690, 13.0790], [80.2715, 13.0760], [80.2740, 13.0730]]
  },
  {
    id: 'seg-5-6',
    name: 'Harbor Bypass Diverter',
    fromJunction: 'J5',
    toJunction: 'J6',
    lengthMeters: 880,
    currentSpeedKmh: 24,
    freeFlowSpeedKmh: 42,
    capacityStressPercent: 82,
    estimatedQueueMeters: 160,
    blockingPercent: 30,
    flowVehiclesPerHour: 1780,
    densityVehiclesPerKm: 74,
    vehicleComposition: { cars: 38, twoWheelers: 36, buses: 12, heavyVehicles: 6, autos: 8 },
    classification: 'ESTIMATED',
    freshness: 'FRESH',
    lastUpdatedSecondsAgo: 6,
    predictedRisk: 'HIGH',
    confidencePercent: 81,
    coordinates: [[80.2740, 13.0730], [80.2725, 13.0695], [80.2710, 13.0660]]
  },
  {
    id: 'seg-5-7',
    name: 'Grand Trunk Direct Spine',
    fromJunction: 'J5',
    toJunction: 'J7',
    lengthMeters: 780,
    currentSpeedKmh: 19,
    freeFlowSpeedKmh: 45,
    capacityStressPercent: 89,
    estimatedQueueMeters: 210,
    blockingPercent: 38,
    flowVehiclesPerHour: 2400,
    densityVehiclesPerKm: 126,
    vehicleComposition: { cars: 44, twoWheelers: 34, buses: 10, heavyVehicles: 4, autos: 8 },
    classification: 'OBSERVED',
    freshness: 'FRESH',
    lastUpdatedSecondsAgo: 4,
    predictedRisk: 'CRITICAL',
    confidencePercent: 89,
    coordinates: [[80.2740, 13.0730], [80.2765, 13.0705], [80.2790, 13.0680]]
  },
  {
    id: 'seg-6-7',
    name: 'Harbor-Plaza Cross Connector',
    fromJunction: 'J6',
    toJunction: 'J7',
    lengthMeters: 920,
    currentSpeedKmh: 16,
    freeFlowSpeedKmh: 40,
    capacityStressPercent: 91,
    estimatedQueueMeters: 235,
    blockingPercent: 44,
    flowVehiclesPerHour: 1820,
    densityVehiclesPerKm: 114,
    vehicleComposition: { cars: 40, twoWheelers: 42, buses: 8, heavyVehicles: 3, autos: 7 },
    classification: 'ESTIMATED',
    freshness: 'FRESH',
    lastUpdatedSecondsAgo: 5,
    predictedRisk: 'CRITICAL',
    confidencePercent: 86,
    coordinates: [[80.2710, 13.0660], [80.2750, 13.0670], [80.2790, 13.0680]]
  },
  {
    id: 'seg-7-8',
    name: 'Plaza to Hospital Link',
    fromJunction: 'J7',
    toJunction: 'J8',
    lengthMeters: 940,
    currentSpeedKmh: 23,
    freeFlowSpeedKmh: 42,
    capacityStressPercent: 86,
    estimatedQueueMeters: 184,
    blockingPercent: 32,
    flowVehiclesPerHour: 2240,
    densityVehiclesPerKm: 98,
    vehicleComposition: { cars: 46, twoWheelers: 32, buses: 11, heavyVehicles: 3, autos: 8 },
    classification: 'ESTIMATED',
    freshness: 'FRESH',
    lastUpdatedSecondsAgo: 3,
    predictedRisk: 'HIGH',
    confidencePercent: 78,
    coordinates: [[80.2790, 13.0680], [80.2820, 13.0650], [80.2850, 13.0620]]
  },
  {
    id: 'seg-8-9',
    name: 'Hospital Immediate Approach',
    fromJunction: 'J8',
    toJunction: 'J9',
    lengthMeters: 1050,
    currentSpeedKmh: 34,
    freeFlowSpeedKmh: 45,
    capacityStressPercent: 62,
    estimatedQueueMeters: 75,
    blockingPercent: 14,
    flowVehiclesPerHour: 1650,
    densityVehiclesPerKm: 48,
    vehicleComposition: { cars: 55, twoWheelers: 25, buses: 12, heavyVehicles: 2, autos: 6 },
    classification: 'OBSERVED',
    freshness: 'FRESH',
    lastUpdatedSecondsAgo: 9,
    predictedRisk: 'MODERATE',
    confidencePercent: 87,
    coordinates: [[80.2850, 13.0620], [80.2885, 13.0590], [80.2920, 13.0560]]
  },
  {
    id: 'seg-2-9',
    name: 'Eastern Bypass Outer Loop',
    fromJunction: 'J2',
    toJunction: 'J9',
    lengthMeters: 4600,
    currentSpeedKmh: 44,
    freeFlowSpeedKmh: 50,
    capacityStressPercent: 41,
    estimatedQueueMeters: 40,
    blockingPercent: 8,
    flowVehiclesPerHour: 1560,
    densityVehiclesPerKm: 35,
    vehicleComposition: { cars: 60, twoWheelers: 20, buses: 10, heavyVehicles: 5, autos: 5 },
    classification: 'OBSERVED',
    freshness: 'FRESH',
    lastUpdatedSecondsAgo: 14,
    predictedRisk: 'LOW',
    confidencePercent: 91,
    coordinates: [[80.2580, 13.0910], [80.2750, 13.0900], [80.2880, 13.0780], [80.2920, 13.0560]]
  },
  {
    id: 'seg-3-10',
    name: 'Southern Link to Ring Road',
    fromJunction: 'J3',
    toJunction: 'J10',
    lengthMeters: 4200,
    currentSpeedKmh: 42,
    freeFlowSpeedKmh: 48,
    capacityStressPercent: 35,
    estimatedQueueMeters: 25,
    blockingPercent: 5,
    flowVehiclesPerHour: 1300,
    densityVehiclesPerKm: 30,
    vehicleComposition: { cars: 50, twoWheelers: 30, buses: 10, heavyVehicles: 4, autos: 6 },
    classification: 'OBSERVED',
    freshness: 'FRESH',
    lastUpdatedSecondsAgo: 16,
    predictedRisk: 'LOW',
    confidencePercent: 90,
    coordinates: [[80.2640, 13.0850], [80.2700, 13.0700], [80.2760, 13.0580], [80.2800, 13.0500]]
  }
];

export const CORRIDOR_INCIDENTS: TrafficIncident[] = [
  {
    id: 'inc-1',
    type: 'ACCIDENT',
    locationName: 'J7 North Approach (Spine Road)',
    junctionId: 'j7',
    roadSegmentId: 'seg-5-7',
    severity: 'HIGH',
    startTime: '10 mins ago',
    expectedDurationMinutes: 35,
    source: 'TRAFFIC_CONTROL_CCTV_CAM_14',
    confidencePercent: 94,
    classification: 'OBSERVED',
    description: 'Multi-vehicle collision blocking middle and right lanes on primary inbound approach to J7.',
    downstreamImpactNodes: ['J6', 'J7', 'J8']
  },
  {
    id: 'inc-2',
    type: 'ROADWORK',
    locationName: 'J6 Harbor Link Merge',
    junctionId: 'j6',
    roadSegmentId: 'seg-6-7',
    severity: 'MODERATE',
    startTime: '2 hours ago',
    expectedDurationMinutes: 120,
    source: 'MUNICIPAL_WORKS_FEED',
    confidencePercent: 88,
    classification: 'OBSERVED',
    description: 'Utility maintenance narrowing lane width from 3.5m to 2.8m, restricting heavy vehicle transit.',
    downstreamImpactNodes: ['J7']
  }
];

export const CASCADE_EVENTS: CascadeEvent[] = [
  {
    id: 'e1',
    type: 'SPILLBACK',
    junctionCode: 'J7',
    roadSegmentId: 'seg-5-7',
    predictedTimeOffsetMinutes: 3,
    probabilityPercent: 72,
    severity: 'CRITICAL',
    confidencePercent: 78,
    propagationDelaySeconds: 180,
    status: 'ANTICIPATED'
  },
  {
    id: 'e2',
    parentId: 'e1',
    type: 'DOWNSTREAM_BLOCKING',
    junctionCode: 'J6',
    roadSegmentId: 'seg-6-7',
    predictedTimeOffsetMinutes: 7,
    probabilityPercent: 64,
    severity: 'HIGH',
    confidencePercent: 72,
    propagationDelaySeconds: 240,
    status: 'ANTICIPATED'
  },
  {
    id: 'e3',
    parentId: 'e1',
    type: 'DIVERSION_OVERLOAD',
    junctionCode: 'J8',
    roadSegmentId: 'seg-7-8',
    predictedTimeOffsetMinutes: 10,
    probabilityPercent: 53,
    severity: 'HIGH',
    confidencePercent: 68,
    propagationDelaySeconds: 180,
    status: 'ANTICIPATED'
  },
  {
    id: 'e4',
    parentId: 'e3',
    type: 'CAPACITY_REDUCTION',
    junctionCode: 'J9',
    roadSegmentId: 'seg-8-9',
    predictedTimeOffsetMinutes: 14,
    probabilityPercent: 38,
    severity: 'MODERATE',
    confidencePercent: 60,
    propagationDelaySeconds: 240,
    status: 'ANTICIPATED'
  }
];

export const CASCADE_RELATIONSHIPS: CascadeRelationship[] = [
  {
    id: 'rel-1',
    sourceEventId: 'e1',
    targetEventId: 'e2',
    type: 'SPILLBACK',
    delaySeconds: 240,
    influenceWeight: 0.82
  },
  {
    id: 'rel-1b',
    sourceEventId: 'e1',
    targetEventId: 'e3',
    type: 'DOWNSTREAM_BLOCKING',
    delaySeconds: 180,
    influenceWeight: 0.74
  },
  {
    id: 'rel-2',
    sourceEventId: 'e3',
    targetEventId: 'e4',
    type: 'DIVERSION_OVERLOAD',
    delaySeconds: 240,
    influenceWeight: 0.58
  }
];

export const DEFAULT_SCENARIOS: ScenarioResult[] = [
  {
    scenarioId: 'scen-baseline',
    name: 'BASELINE (Do Nothing)',
    type: 'BASELINE',
    affectedNodesCount: 6,
    cascadeDurationMinutes: 14,
    maxSeverityScore: 0.86,
    recoveryTimeMinutes: 22,
    travelTimeImpactPercent: 34, // +34% delay
    emergencyCorridorImpactScore: 0.88, // high risk to ambulance
    primaryBenefit: 'No intervention overhead',
    secondaryEffect: 'Unconstrained cascade across J7 → J6 → J8, total gridlock of Plaza sector',
    secondaryEffectProbabilityPercent: 88,
    uncertaintyScore: 0.18,
    classification: 'SIMULATED'
  },
  {
    scenarioId: 'scen-a',
    name: 'SCENARIO A — Signal Extension',
    type: 'SIGNAL',
    affectedNodesCount: 4,
    cascadeDurationMinutes: 8,
    maxSeverityScore: 0.64,
    recoveryTimeMinutes: 11,
    travelTimeImpactPercent: -18,
    emergencyCorridorImpactScore: 0.42,
    primaryBenefit: 'Flushes J7 queue by extending inbound green phase by 15s for 180s',
    secondaryEffect: 'Slight upstream buildup on secondary feeder streets (Civic Link)',
    secondaryEffectProbabilityPercent: 32,
    uncertaintyScore: 0.24,
    classification: 'SIMULATED'
  },
  {
    scenarioId: 'scen-b',
    name: 'SCENARIO B — Perimeter Diversion',
    type: 'DIVERSION',
    affectedNodesCount: 5,
    cascadeDurationMinutes: 10,
    maxSeverityScore: 0.71,
    recoveryTimeMinutes: 14,
    travelTimeImpactPercent: -12,
    emergencyCorridorImpactScore: 0.51,
    primaryBenefit: 'Diverts 25% of traffic before J5 onto Eastern Bypass loop',
    secondaryEffect: 'Elevates traffic pressure on Junction J8 and hospital approach corridor',
    secondaryEffectProbabilityPercent: 49,
    uncertaintyScore: 0.28,
    classification: 'SIMULATED'
  },
  {
    scenarioId: 'scen-ab',
    name: 'SCENARIO A+B — Coordinated Strategy',
    type: 'COMBINED',
    affectedNodesCount: 3,
    cascadeDurationMinutes: 6,
    maxSeverityScore: 0.52,
    recoveryTimeMinutes: 8,
    travelTimeImpactPercent: -28,
    emergencyCorridorImpactScore: 0.22,
    primaryBenefit: 'Simultaneous 15s green flush at J7 with 20% early diversion at J3 & J5',
    secondaryEffect: 'Minor +3% travel time increase for diverted peripheral commuters',
    secondaryEffectProbabilityPercent: 26,
    uncertaintyScore: 0.21,
    classification: 'SIMULATED'
  }
];

export const DEMO_ROUTE_ALTERNATIVES: RouteAlternative[] = [
  {
    id: 'route-a',
    name: 'Direct Central Arterial (Route A)',
    tag: 'FASTEST',
    tagLabel: 'HIGHER FUTURE RISK',
    viaRoads: ['Grand Trunk Spine', 'Central Plaza Apex'],
    distanceKm: 11.1,
    estimatedDurationMinutes: 23,
    currentTravelTimeMinutes: 18,
    predictedTravelTimeMinutes: 28,
    currentTrafficSeverity: 'MODERATE',
    futureRiskSeverity: 'HIGH',
    gridlockRiskPercent: 57,
    predictedRiskPercent: 72,
    tradeoffDescription: 'Fastest current route (18 min now), but predicted Central Plaza spillback will cause +10 min delay within 4 minutes.',
    confidencePercent: 75,
    predictedDisruptionsCount: 2,
    cascadeExposure: 'HIGH',
    majorRiskJunctions: ['J7', 'J6'],
    riskTimeWindow: '+3 to +8 min',
    polylineCoordinates: [
      [80.2520, 13.0980],
      [80.2580, 13.0910],
      [80.2640, 13.0850],
      [80.2690, 13.0790],
      [80.2740, 13.0730],
      [80.2790, 13.0680],
      [80.2850, 13.0620],
      [80.2920, 13.0560]
    ],
    segments: [
      { roadName: 'North Arterial Section 1', lengthMeters: 950, currentSpeedKmh: 46, predictedSpeedKmh: 42, risk: 'LOW' },
      { roadName: 'Tech Blvd Main Connector', lengthMeters: 1100, currentSpeedKmh: 38, predictedSpeedKmh: 34, risk: 'LOW' },
      { roadName: 'Civic Link Expressway', lengthMeters: 850, currentSpeedKmh: 31, predictedSpeedKmh: 26, risk: 'MODERATE' },
      { roadName: 'Grand Trunk Direct Spine', lengthMeters: 780, currentSpeedKmh: 19, predictedSpeedKmh: 11, risk: 'CRITICAL' },
      { roadName: 'Plaza to Hospital Link', lengthMeters: 940, currentSpeedKmh: 23, predictedSpeedKmh: 15, risk: 'HIGH' },
      { roadName: 'Hospital Immediate Approach', lengthMeters: 1050, currentSpeedKmh: 34, predictedSpeedKmh: 28, risk: 'MODERATE' }
    ],
    explanationRisk: 'Passes directly through Junction J7 where an accident and imminent spillback (72% probability) will stall the approach within 3-6 minutes.',
    explanationTradeoff: 'Current ETA is fastest (18 min), but carries a 72% Gridlock Risk that could inflate travel time to 28+ minutes if the cascade matures.',
    steps: [
      { instruction: 'Head south on North Arterial Section 1', distance: '1.2 km', estimatedDuration: '2 min' },
      { instruction: 'Continue onto Grand Trunk Spine toward Central Plaza', distance: '4.8 km', estimatedDuration: '8 min' },
      { instruction: 'Pass through Central Plaza Apex (Caution: high congestion)', distance: '1.5 km', estimatedDuration: '12 min' },
      { instruction: 'Arrive at destination via Plaza-Hospital Link', distance: '3.6 km', estimatedDuration: '6 min' }
    ]
  },
  {
    id: 'route-b',
    name: 'Eastern Bypass Corridor (Route B)',
    tag: 'LOWER_FUTURE_RISK',
    tagLabel: 'RECOMMENDED / LOWER RISK',
    viaRoads: ['Eastern Outer Bypass Loop'],
    distanceKm: 12.4,
    estimatedDurationMinutes: 26,
    currentTravelTimeMinutes: 22,
    predictedTravelTimeMinutes: 23,
    currentTrafficSeverity: 'LOW',
    futureRiskSeverity: 'LOW',
    gridlockRiskPercent: 18,
    predictedRiskPercent: 8,
    tradeoffDescription: '4 minutes slower right now, but bypasses the impending J7 spillback, saving 5+ minutes when gridlock hits.',
    confidencePercent: 84,
    predictedDisruptionsCount: 0,
    cascadeExposure: 'LOW',
    majorRiskJunctions: [],
    riskTimeWindow: 'None anticipated',
    polylineCoordinates: [
      [80.2520, 13.0980],
      [80.2580, 13.0910],
      [80.2750, 13.0900],
      [80.2880, 13.0780],
      [80.2920, 13.0560]
    ],
    segments: [
      { roadName: 'North Arterial Section 1', lengthMeters: 950, currentSpeedKmh: 46, predictedSpeedKmh: 45, risk: 'LOW' },
      { roadName: 'Eastern Bypass Outer Loop', lengthMeters: 4600, currentSpeedKmh: 44, predictedSpeedKmh: 42, risk: 'LOW' },
      { roadName: 'Hospital Immediate Approach', lengthMeters: 1050, currentSpeedKmh: 34, predictedSpeedKmh: 32, risk: 'LOW' }
    ],
    explanationRisk: 'Completely circumvents the Plaza cluster and J7 bottleneck by taking the wide 6-lane Eastern Bypass.',
    explanationTradeoff: 'Adds 4 minutes to baseline drive time (+1.3 km), but provides 92% journey reliability with only 8% Gridlock Risk.',
    steps: [
      { instruction: 'Head south on North Arterial Section 1', distance: '1.2 km', estimatedDuration: '2 min' },
      { instruction: 'Take the ramp onto Eastern Bypass Outer Loop', distance: '8.4 km', estimatedDuration: '14 min' },
      { instruction: 'Merge onto Hospital Immediate Approach', distance: '2.8 km', estimatedDuration: '7 min' }
    ]
  },
  {
    id: 'route-c',
    name: 'South Ringway Link (Route C)',
    tag: 'ALTERNATIVE',
    tagLabel: 'METRO WEST CONNECTOR',
    viaRoads: ['Metro West Arterial', 'South Ringway'],
    distanceKm: 13.0,
    estimatedDurationMinutes: 28,
    currentTravelTimeMinutes: 24,
    predictedTravelTimeMinutes: 25,
    currentTrafficSeverity: 'LOW',
    futureRiskSeverity: 'LOW',
    gridlockRiskPercent: 11,
    predictedRiskPercent: 11,
    tradeoffDescription: 'Steady arterial perimeter highway option, entirely isolated from the central bottleneck.',
    confidencePercent: 79,
    predictedDisruptionsCount: 0,
    cascadeExposure: 'LOW',
    majorRiskJunctions: ['J10'],
    riskTimeWindow: 'Minimal',
    polylineCoordinates: [
      [80.2520, 13.0980],
      [80.2580, 13.0910],
      [80.2640, 13.0850],
      [80.2700, 13.0700],
      [80.2760, 13.0580],
      [80.2800, 13.0500],
      [80.2920, 13.0560]
    ],
    segments: [
      { roadName: 'North Arterial Section 1', lengthMeters: 950, currentSpeedKmh: 46, predictedSpeedKmh: 46, risk: 'LOW' },
      { roadName: 'Tech Blvd Main Connector', lengthMeters: 1100, currentSpeedKmh: 38, predictedSpeedKmh: 38, risk: 'LOW' },
      { roadName: 'Southern Link to Ring Road', lengthMeters: 4200, currentSpeedKmh: 42, predictedSpeedKmh: 41, risk: 'LOW' },
      { roadName: 'Ring Road to Hospital Connector', lengthMeters: 1200, currentSpeedKmh: 38, predictedSpeedKmh: 36, risk: 'LOW' }
    ],
    explanationRisk: 'Routes through the southern perimeter highway, entirely isolated from the central bottleneck.',
    explanationTradeoff: 'Longest distance (+1.9 km, 24 min total), but achieves low gridlock risk (11%) in the entire network.',
    steps: [
      { instruction: 'Take North Arterial to Tech Blvd Main Connector', distance: '2.1 km', estimatedDuration: '4 min' },
      { instruction: 'Turn onto Southern Link to Ring Road', distance: '7.8 km', estimatedDuration: '14 min' },
      { instruction: 'Arrive at destination via Ring Road to Hospital Connector', distance: '3.1 km', estimatedDuration: '7 min' }
    ]
  }
];

export const INITIAL_CITIZEN_ALERTS: CitizenAlert[] = [
  {
    id: 'al-1',
    timestamp: '2 mins ago',
    title: 'Predicted Severe Disruption Ahead',
    message: 'AURA predicts high probability of traffic spillback near Central Plaza (J7) within 3-6 minutes. Delay impact: 15-20 min.',
    type: 'PREDICTED_DISRUPTION',
    severity: 'HIGH',
    junctionCode: 'J7',
    classification: 'PREDICTED',
    read: false,
    actionUrl: '/citizen/routes'
  },
  {
    id: 'al-2',
    timestamp: '6 mins ago',
    title: 'Active Emergency Corridor Initiated',
    message: 'Priority green wave deployed for critical ambulance transport from Metro West to City General Hospital (J4 → J5 → J7 → Hospital). Please keep lanes clear.',
    type: 'EMERGENCY_CORRIDOR',
    severity: 'CRITICAL',
    junctionCode: 'J5',
    classification: 'OBSERVED',
    read: false
  },
  {
    id: 'al-3',
    timestamp: '14 mins ago',
    title: 'Incident Reported on Spine Approach',
    message: '2-vehicle collision on inbound approach to Central Plaza. Emergency responders on scene.',
    type: 'INCIDENT_NEARBY',
    severity: 'MODERATE',
    junctionCode: 'J7',
    classification: 'OBSERVED',
    read: true
  }
];

export const INITIAL_SYSTEM_HEALTH: SystemServiceStatus[] = [
  {
    name: 'Traffic Ingestion Provider',
    provider: 'TomTom Live Flow API / Mock Adaptive Adapter',
    status: 'AVAILABLE',
    latencyMs: 84,
    lastHeartbeatSecondsAgo: 3,
    mode: 'DEMO',
    notes: 'Configurable provider active with calibrated realistic arterial corridor stream'
  },
  {
    name: 'State Reconstruction Engine',
    provider: 'AURA Extended Kalman & Flow-Density Estimator',
    status: 'AVAILABLE',
    latencyMs: 12,
    lastHeartbeatSecondsAgo: 2,
    mode: 'DEMO',
    notes: 'Physics constraints validated: flow >= 0, density >= 0, queue <= storage'
  },
  {
    name: 'Spatiotemporal ML Inference',
    provider: 'Graph Transformer + Temporal Transformer + Hazard Head',
    status: 'AVAILABLE',
    latencyMs: 38,
    lastHeartbeatSecondsAgo: 2,
    mode: 'DEMO',
    notes: 'Inference pipeline initialized. Horizon: +15m at 1m intervals'
  },
  {
    name: 'Cascade Propagation Engine',
    provider: 'Intervention-Conditioned Point Process (DAG)',
    status: 'AVAILABLE',
    latencyMs: 24,
    lastHeartbeatSecondsAgo: 3,
    mode: 'DEMO',
    notes: 'Cascade tree E1 -> E2 -> E3/E4 active. Critical node: J7'
  },
  {
    name: 'SUMO Micro-Simulation Twin',
    provider: 'SUMO TraCI Scenario Controller',
    status: 'AVAILABLE',
    latencyMs: 110,
    lastHeartbeatSecondsAgo: 5,
    mode: 'DIGITAL_TWIN',
    notes: 'Pre-calibrated counterfactual sandbox available for A, B, and A+B evaluation'
  },
  {
    name: 'Gemini AI Intelligence',
    provider: 'Google GenAI SDK (gemini-3.8-flash / gemini-3.1-pro-preview)',
    status: 'AVAILABLE',
    latencyMs: 310,
    lastHeartbeatSecondsAgo: 1,
    mode: 'LIVE',
    notes: 'Server-side API bridge active for structured Copilot & explanations'
  },
  {
    name: 'PostgreSQL / PostGIS Database',
    provider: 'Relational Spatial Registry',
    status: 'AVAILABLE',
    latencyMs: 14,
    lastHeartbeatSecondsAgo: 2,
    mode: 'DEMO',
    notes: 'Corridor graph, segment geometry, and incident records mapped'
  },
  {
    name: 'Redis Cache & Event Pub/Sub',
    provider: 'In-memory State & WebSocket Fanout',
    status: 'AVAILABLE',
    latencyMs: 4,
    lastHeartbeatSecondsAgo: 1,
    mode: 'DEMO',
    notes: 'Telemetry cache TTL: 5s. Broadcast stream synchronized'
  }
];

export const INITIAL_AUDIT_LOGS: OperatorAction[] = [
  {
    id: 'aud-101',
    timestamp: '2026-09-19 23:35:12',
    operatorUsername: 'admin',
    operatorId: 'OP-042',
    action: 'ACCEPT',
    actionType: 'CREATE_SCENARIO',
    scenarioId: 'scen-ab',
    details: 'Initiated counterfactual evaluation of Combined Signal Extension + Early Diversion',
    correlationId: 'corr-89241',
    reason: 'Proactive mitigation of J7 spillback to clear ambulance corridor',
    parameters: { signalPhase: 'Phase 2 (Inbound Flush)', greenExtensionSeconds: 15, diversionFraction: 20 }
  },
  {
    id: 'aud-100',
    timestamp: '2026-09-19 23:32:40',
    operatorUsername: 'admin',
    operatorId: 'OP-042',
    action: 'MODIFY',
    actionType: 'CREATE_SCENARIO',
    scenarioId: 'scen-a',
    details: 'Evaluated Scenario A: 15s green extension at J7',
    correlationId: 'corr-89230',
    reason: 'Evaluating single-junction flush efficacy',
    parameters: { greenExtensionSeconds: 15 }
  },
  {
    id: 'aud-099',
    timestamp: '2026-09-19 23:30:15',
    operatorUsername: 'system',
    operatorId: 'SYS-AUTOPILOT',
    action: 'DISPATCH',
    actionType: 'CITIZEN_ALERT_DISPATCH',
    details: 'Automated broadcast: High spillback risk alert dispatched for J7 Plaza approach',
    correlationId: 'corr-89201',
    reason: 'Hazard rate crossed critical 0.70 threshold',
    parameters: { threshold: 0.70, observedHazard: 0.72 }
  },
  {
    id: 'aud-098',
    timestamp: '2026-09-19 23:28:00',
    operatorUsername: 'admin',
    operatorId: 'OP-042',
    action: 'OVERRIDE',
    actionType: 'EMERGENCY_OVERRIDE',
    details: 'Emergency green-wave corridor initialized for Ambulance Call #409 (J4 → J5 → J7 → Hospital)',
    correlationId: 'corr-89188',
    reason: 'Code 3 priority medical dispatch to Trauma Center',
    parameters: { route: 'J4 -> J5 -> J7 -> Hospital', preemptionRadiusMeters: 450 }
  }
];
